### ISSUE TITLE
Read no of grating positions from .sct file

### ISSUE THREAD

**Issue by robminchin** [darioflute/obsmaker#2]
The no of grating positions should be read from the .sct file, which it is given (twice) as RED_POSUP and BLUE_POSUP (possibly it should be N_POSUP + N_POSDOWN, but if we always leave the N_POSDOWN set to zero and only change N_POSUP from USPOT then just using N_POSUP would work)

**Comment by darioflute** [comment]
The current implementation computes the number of grating positions for the red and blue channels. Then, it selects the maximum number of grating positions as initial parameter for the computation.
